//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.HotelTrxnService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.mcda5510.com", ConfigurationName="HotelTrxnService.TrxnWebService")]
    public interface TrxnWebService {
        
        // CODEGEN: 参数“args”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication5.HotelTrxnService.mainResponse main(WebApplication5.HotelTrxnService.mainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication5.HotelTrxnService.mainResponse> mainAsync(WebApplication5.HotelTrxnService.mainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void test();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task testAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void closeConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task closeConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnIntReturn")]
        int returnInt();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnIntReturn")]
        System.Threading.Tasks.Task<int> returnIntAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDaoReturn")]
        WebApplication5.HotelTrxnService.MySQLAccess getDao();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDaoReturn")]
        System.Threading.Tasks.Task<WebApplication5.HotelTrxnService.MySQLAccess> getDaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setDao(WebApplication5.HotelTrxnService.MySQLAccess dao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task setDaoAsync(WebApplication5.HotelTrxnService.MySQLAccess dao);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionReturn")]
        string getTransaction(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionReturn")]
        System.Threading.Tasks.Task<string> getTransactionAsync(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createTransactionReturn")]
        bool createTransaction(WebApplication5.HotelTrxnService.Transaction trxn);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createTransactionReturn")]
        System.Threading.Tasks.Task<bool> createTransactionAsync(WebApplication5.HotelTrxnService.Transaction trxn);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeTransactionReturn")]
        bool removeTransaction(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeTransactionReturn")]
        System.Threading.Tasks.Task<bool> removeTransactionAsync(string tid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateTransactionReturn")]
        bool updateTransaction(WebApplication5.HotelTrxnService.Transaction trxn);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateTransactionReturn")]
        System.Threading.Tasks.Task<bool> updateTransactionAsync(WebApplication5.HotelTrxnService.Transaction trxn);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://service.mcda5510.com", IsWrapped=true)]
    public partial class mainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.mcda5510.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("args")]
        public string[] args;
        
        public mainRequest() {
        }
        
        public mainRequest(string[] args) {
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mainResponse", WrapperNamespace="http://service.mcda5510.com", IsWrapped=true)]
    public partial class mainResponse {
        
        public mainResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dao.mcda5510.com")]
    public partial class MySQLAccess : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entity.mcda5510.com")]
    public partial class Transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> cardCategoryField;
        
        private string cardNumberField;
        
        private string createdByField;
        
        private string createdOnField;
        
        private string creditCardTypeNameField;
        
        private string expDateField;
        
        private string idField;
        
        private string nameOnCardField;
        
        private System.Nullable<int> quantityField;
        
        private System.Nullable<int> reservationIdField;
        
        private System.Nullable<double> totalPriceField;
        
        private System.Nullable<double> unitPriceField;
        
        private System.Nullable<int> userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> cardCategory {
            get {
                return this.cardCategoryField;
            }
            set {
                this.cardCategoryField = value;
                this.RaisePropertyChanged("cardCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("createdBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string createdOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("createdOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string creditCardTypeName {
            get {
                return this.creditCardTypeNameField;
            }
            set {
                this.creditCardTypeNameField = value;
                this.RaisePropertyChanged("creditCardTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string expDate {
            get {
                return this.expDateField;
            }
            set {
                this.expDateField = value;
                this.RaisePropertyChanged("expDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string nameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
                this.RaisePropertyChanged("nameOnCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> reservationId {
            get {
                return this.reservationIdField;
            }
            set {
                this.reservationIdField = value;
                this.RaisePropertyChanged("reservationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<double> totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
                this.RaisePropertyChanged("totalPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<double> unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("unitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrxnWebServiceChannel : WebApplication5.HotelTrxnService.TrxnWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrxnWebServiceClient : System.ServiceModel.ClientBase<WebApplication5.HotelTrxnService.TrxnWebService>, WebApplication5.HotelTrxnService.TrxnWebService {
        
        public TrxnWebServiceClient() {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrxnWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication5.HotelTrxnService.mainResponse WebApplication5.HotelTrxnService.TrxnWebService.main(WebApplication5.HotelTrxnService.mainRequest request) {
            return base.Channel.main(request);
        }
        
        public void main(string[] args) {
            WebApplication5.HotelTrxnService.mainRequest inValue = new WebApplication5.HotelTrxnService.mainRequest();
            inValue.args = args;
            WebApplication5.HotelTrxnService.mainResponse retVal = ((WebApplication5.HotelTrxnService.TrxnWebService)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication5.HotelTrxnService.mainResponse> WebApplication5.HotelTrxnService.TrxnWebService.mainAsync(WebApplication5.HotelTrxnService.mainRequest request) {
            return base.Channel.mainAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication5.HotelTrxnService.mainResponse> mainAsync(string[] args) {
            WebApplication5.HotelTrxnService.mainRequest inValue = new WebApplication5.HotelTrxnService.mainRequest();
            inValue.args = args;
            return ((WebApplication5.HotelTrxnService.TrxnWebService)(this)).mainAsync(inValue);
        }
        
        public void test() {
            base.Channel.test();
        }
        
        public System.Threading.Tasks.Task testAsync() {
            return base.Channel.testAsync();
        }
        
        public void closeConnection() {
            base.Channel.closeConnection();
        }
        
        public System.Threading.Tasks.Task closeConnectionAsync() {
            return base.Channel.closeConnectionAsync();
        }
        
        public int returnInt() {
            return base.Channel.returnInt();
        }
        
        public System.Threading.Tasks.Task<int> returnIntAsync() {
            return base.Channel.returnIntAsync();
        }
        
        public WebApplication5.HotelTrxnService.MySQLAccess getDao() {
            return base.Channel.getDao();
        }
        
        public System.Threading.Tasks.Task<WebApplication5.HotelTrxnService.MySQLAccess> getDaoAsync() {
            return base.Channel.getDaoAsync();
        }
        
        public void setDao(WebApplication5.HotelTrxnService.MySQLAccess dao) {
            base.Channel.setDao(dao);
        }
        
        public System.Threading.Tasks.Task setDaoAsync(WebApplication5.HotelTrxnService.MySQLAccess dao) {
            return base.Channel.setDaoAsync(dao);
        }
        
        public string getTransaction(string tid) {
            return base.Channel.getTransaction(tid);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionAsync(string tid) {
            return base.Channel.getTransactionAsync(tid);
        }
        
        public bool createTransaction(WebApplication5.HotelTrxnService.Transaction trxn) {
            return base.Channel.createTransaction(trxn);
        }
        
        public System.Threading.Tasks.Task<bool> createTransactionAsync(WebApplication5.HotelTrxnService.Transaction trxn) {
            return base.Channel.createTransactionAsync(trxn);
        }
        
        public bool removeTransaction(string tid) {
            return base.Channel.removeTransaction(tid);
        }
        
        public System.Threading.Tasks.Task<bool> removeTransactionAsync(string tid) {
            return base.Channel.removeTransactionAsync(tid);
        }
        
        public bool updateTransaction(WebApplication5.HotelTrxnService.Transaction trxn) {
            return base.Channel.updateTransaction(trxn);
        }
        
        public System.Threading.Tasks.Task<bool> updateTransactionAsync(WebApplication5.HotelTrxnService.Transaction trxn) {
            return base.Channel.updateTransactionAsync(trxn);
        }
    }
}
